### ISSUE TITLE
Cookiecutter setup yes/no choose order

### ISSUE THREAD

**Issue by danczw** [at-gmbh/at-python-template#56]
During setup with cookiecutter, the yes/no (1/2) order for answering setup questions is different from the rest in one option ('Select use_notebook'):

![image](https://user-images.githubusercontent.com/25065665/148554760-4c31686d-b365-4870-ac87-93e2fdb65e79.png)

Consider changing the order to be same for all yes/no questions. This is where one often chooses the wrong option when using the template regularly. ;)

Cheers

**Comment by klamann** [comment]
This was our way of specifying default values, since the first item is always the default in cookiecutter. E.g. we felt that most users of our template would want to use notebooks, but don't need Docker images.

But I can see how this can feel inconsistent. We have a bunch of open PRs in cookiecutter to improve the cookiecutter.json definition to allow for a better UX (see [cookiecutter#1567](https://github.com/cookiecutter/cookiecutter/issues/1567)), but I'm not sure they will be accepted in the near future.

I guess we could change this to make "no" the first entry for all these yes/no questions in the meantime.

**Comment by klamann** [comment]
this was solved in #63
